model_list:
#Bedrock Models
  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0

  - model_name: meta.llama3-3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-3-70b-instruct-v1:0

  - model_name: us.anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-haiku-20240307-v1:0

  - model_name: us.meta.llama3-2-1b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-1b-instruct-v1:0

  - model_name: us.meta.llama3-2-11b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-11b-instruct-v1:0

  - model_name: us.meta.llama3-2-3b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-3b-instruct-v1:0

  - model_name: us.meta.llama3-2-90b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-2-90b-instruct-v1:0

  - model_name: us.meta.llama3-1-8b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-8b-instruct-v1:0

  - model_name: us.meta.llama3-1-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-70b-instruct-v1:0

  - model_name: us.amazon.nova-micro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-micro-v1:0

  - model_name: us.amazon.nova-lite-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-lite-v1:0

  - model_name: us.amazon.nova-pro-v1:0
    litellm_params:
      model: bedrock/us.amazon.nova-pro-v1:0

  - model_name: us.anthropic.claude-3-5-haiku-20241022-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0

  - model_name: us.meta.llama3-1-405b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-1-405b-instruct-v1:0

  - model_name: us.meta.llama3-3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/us.meta.llama3-3-70b-instruct-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20240620-v1:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0

  - model_name: us.anthropic.claude-3-5-sonnet-20241022-v2:0
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0

  - model_name: us.anthropic.claude-3-7-sonnet-20250219-v1:0
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0

