model_list:
#Bedrock Models
  - model_name: amazon.titan-text-lite-v1
    litellm_params:
      model: bedrock/amazon.titan-text-lite-v1

  - model_name: amazon.titan-text-express-v1
    litellm_params:
      model: bedrock/amazon.titan-text-express-v1

  - model_name: amazon.titan-embed-image-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-image-v1

  - model_name: amazon.titan-image-generator-v1
    litellm_params:
      model: bedrock/amazon.titan-image-generator-v1

  - model_name: amazon.titan-embed-text-v2:0
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0

  - model_name: anthropic.claude-3-sonnet-20240229-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet-20240229-v1:0

  - model_name: anthropic.claude-3-haiku-20240307-v1:0
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0

  - model_name: cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3

  - model_name: cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3

  - model_name: meta.llama3-8b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-8b-instruct-v1:0

  - model_name: meta.llama3-70b-instruct-v1:0
    litellm_params:
      model: bedrock/meta.llama3-70b-instruct-v1:0

  - model_name: mistral.mistral-7b-instruct-v0:2
    litellm_params:
      model: bedrock/mistral.mistral-7b-instruct-v0:2

  - model_name: mistral.mixtral-8x7b-instruct-v0:1
    litellm_params:
      model: bedrock/mistral.mixtral-8x7b-instruct-v0:1

  - model_name: mistral.mistral-large-2402-v1:0
    litellm_params:
      model: bedrock/mistral.mistral-large-2402-v1:0

